## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Axel Steciuk"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Axel Steciuk CV"
  logo = "images/cv.svg"
  favicon = true

[Params.social]
  github = "https://github.com/trashcluster/"
  #twitter = "https://twitter.com/caressofsteel_"
  email = "axel.steciuk@gmail.com"
  #instagram = "https://instagram.com"
  linkedin = "https://www.linkedin.com/in/axel-steciuk/"
  telegram = "https://t.me/axelst"